### PR TITLE
New Workshop Format

### LINKED ISSUE #10: Add more intuitive examples for tree, bagging, boosting, and ensemble models

### LINKED ISSUE #11: 04.Decision_Trees.RMD `makeCluster()` function error
Running the part 4 .RMD locally, I'm getting an error on line 197 with:
```
cl <- makeCluster(detectCores() - 1)
registerDoParallel(cl)
```
I believe this function optimizes a local environment for heavier computation? I've dug into the docs and arguments get deep into CS, beyond my scope at this time. It's possible to continue downstream in the workflow without these lines being run, which is what I've done so far.

### LINKED ISSUE #12: Participant Instructions to run 01_overview.RMD
It may help students and instructors if we include the "Participants Instructions" closer to the top of the read me, in large script with a message something like:

"If you are working in a local computing environment, be sure to prepare for the workshop by running all the code in the 01.Overview.RMD before our first meeting. Doing this could take a few minutes, and is needed for you to run the workshop's code on your own computer."

### PR DESCRIPTION
**Pull request by asteves**
This PR does the following 

- Puts this workshop into D-Lab style 
- Fully updates README and puts it into new D-Lab style
- Fully updates all text 
- Reorganizes the workshop into 3 parts: an overview of Machine learning methods, tidymodels syntax, and then several algorithms. Focuses on Supervised Learning only 
- Provides new challenges 

In addition, Closes #10 #11 #12

### CODE REVIEW

**Comment by asteves** [comment]
There are still several additions that need to be made following this PR. Will make them into issues upon approval.

**Comment by pssachdeva** [comment]
Can you update the workshop so that it's called R-Machine-Learning, and have this reflected as necessary in Rproj files, titles, etc.?

**Comment by asteves** [comment]
> Can you update the workshop so that it's called R-Machine-Learning, and have this reflected as necessary in Rproj files, titles, etc.?

Done. @pssachdeva

**Comment by pssachdeva** [comment]
I skimmed over it. This looks great. Feel free to merge - any kinks will be worked out as this workshop occurs this semester.

**Pull request merged**
